name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: target/ec2-deploy-springboot-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
          path: .

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy JAR to EC2
        run: |
          scp -i ~/.ssh/id_rsa -P ${{ secrets.EC2_PORT }} ec2-deploy-springboot-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/ec2-deploy-springboot-0.0.1-SNAPSHOT.jar

      - name: Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.EC2_PORT }} ec2-user@${{ secrets.EC2_HOST }} << 'EOF'          
            echo "Connected to EC2: $(hostname)"
            # Install Java 17 (Amazon Corretto)
            if ! java -version 2>&1 | grep "17" > /dev/null; then
              sudo yum install java-17-amazon-corretto -y
            else
              echo "Java 17 already installed."
            fi
          
            # Set JAVA_HOME and update PATH
            export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
            export PATH=$JAVA_HOME/bin:$PATH          
            pkill -f ec2-deploy-springboot.jar || true
            nohup java -jar /home/ec2-user/ec2-deploy-springboot-0.0.1-SNAPSHOT.jar > /home/ec2-user/application.log 2>&1 &
          EOF